### ISSUE TITLE
Anchor Links for Routes in YAML Files

### ISSUE THREAD

**Issue by Darkrogua** [Ssentiago/openapi-renderer#14]
Hello, thanks for the plugin! As I understand it, there is currently no way to create anchor links to specific routes in a YAML file when viewing OpenAPI specs. This would be really useful for navigating large files, especially when there are many endpoints listed.

Is there any plan to support this feature, or would you consider adding it? It would help a lot with referencing specific API routes directly from other notes in Obsidian.

**Comment by Ssentiago** [comment]
> Hello, thanks for the plugin! As I understand it, there is currently no way to create anchor links to specific routes in a YAML file when viewing OpenAPI specs. This would be really useful for navigating large files, especially when there are many endpoints listed.
> 
> Is there any plan to support this feature, or would you consider adding it? It would help a lot with referencing specific API routes directly from other notes in Obsidian.

Hello! Do you mean $ref links and their management?

**Comment by Darkrogua** [comment]
> Hello! Do you mean $ref links and their management?

No, I don't mean `$ref` links. I'm asking about the ability to create anchor links (similar to HTML anchors) to specific routes or sections in a YAML file. This would allow for easier navigation within large OpenAPI specs by referencing a particular API route directly, rather than managing schema references through `$ref`.

**Comment by Ssentiago** [comment]
> > Hello! Do you mean $ref links and their management?
> 
> No, I don't mean `$ref` links. I'm asking about the ability to create anchor links (similar to HTML anchors) to specific routes or sections in a YAML file. This would allow for easier navigation within large OpenAPI specs by referencing a particular API route directly, rather than managing schema references through `$ref`.

Why not? It looks like an interesting feature. I'll think about it, thanks for leaving the idea.

**Comment by OZ1245** [comment]
Is there any progress on this feature? I saw the pull request that this was supposedly implemented, but I won’t be able to figure out how to add an anchor and how to refer to it later.

**Comment by OZ1245** [comment]
Oh, I found how to add an anchor. But the link to it is very strange. Does not go through it from another document.
I try to make a link both internally (`[[]]`) and externally (`()[]`).

**Comment by Ssentiago** [comment]
> Oh, I found how to add an anchor. But the link to it is very strange. Does not go through it from another document.
> I try to make a link both internally (`[[]]`) and externally (`()[]`).


Thanks for the comments. Perhaps in the future I will review how this feature works and make it clearer.
