### ISSUE TITLE
Error Failure to initialize swagger UI

### ISSUE THREAD

**Issue by aka-mj** [Ssentiago/openapi-renderer#18]
I'm on Ubuntu Linux, I have swagger UI running from docker. When I try to render I get an error from the plugin saying "Failure to initialize swagger UI". Unsure how to go about troubleshooting it further.

**Comment by Ssentiago** [comment]
This is strange, this does not happen normally. Please send the logs (located in the plugin folder/logs)

**Comment by Ssentiago** [comment]
Also, please make sure that you have downloaded the resources by clicking the 'Download Resources' button in the plugin settings (this requires internet connection)

**Comment by aka-mj** [comment]
> Also, please make sure that you have downloaded the resources by clicking the 'Download Resources' button in the plugin settings (this requires internet connection)

This resolved my issue.
Thank you!
