### ISSUE TITLE
Error when trying to open Preview

### ISSUE THREAD

**Issue by codepanda26** [Ssentiago/openapi-renderer#20]
I recently installed your pluggin. When I try to open the preview mode. I get the following error message:
```
{
  "timestamp": "2024-11-21T10:12:57.772Z",
  "level": "ERROR",
  "message": "Protocol \"c:\" not supported. Expected \"https:\"",
  "context": "Error\n    at GP.loadSpec (plugin:openapi-renderer:487:465605)\n    at async xP.renderSwaggerUI (plugin:openapi-renderer:487:468725)\n    at async xP.render (plugin:openapi-renderer:487:468123)\n    at async XP.render (plugin:openapi-renderer:487:471169)\n    at async WP.render (plugin:openapi-renderer:487:471749)",
  "system": {
    "platform": "win32",
    "release": "10.0.22631",
    "arch": "x64"
  }
}
```

I used the yaml spec file found in your test-vault

**Comment by Ssentiago** [comment]
Thanks for the issue, I'll check it out. I didn't test on Windows (guess you're using Windows 10, right?).

**Comment by codepanda26** [comment]
Its actually windows 11 pro that I'm on. Not sure why the log has it as 10.0.22631

**Comment by Ssentiago** [comment]
> Its actually windows 11 pro that I'm on. Not sure why the log has it as 10.0.22631

I am checked this on win 11 with the specification from the test vault. There are no problems, the preview opens correctly

Please make sure that you have downloaded the resources necessary for the plugin to work (they are not included in the plugin, because they would seriously increase the size of the bundle): go to the plugin settings -> click the menu item "Download plugin assets". If it doesn't help, then let me know, I'll think about it

**Comment by codepanda26** [comment]
Hi,
Yup the asset folder has been downloaded. I tried it on two different window machines and I have the same error on both. I can open preview from the OpenAPI Version View.

**Comment by Ssentiago** [comment]
Got this error. I'll check out

**Comment by Ssentiago** [comment]
> Hi, Yup the asset folder has been downloaded. I tried it on two different window machines and I have the same error on both. I can open preview from the OpenAPI Version View.

Hey, I think I solved it. You can check out the latest release. Is the problem still there? I checked, and it seems to be working fine now on my end.

**Comment by codepanda26** [comment]
Hi, I tried it with the update and it seems to be working now. Thanks for fixing it!
